--PIDM.SPBPERS
----- GRAB ALL PIDMS NEEDED FOR LATER QUERIES ------------
select SFRSTCR_PIDM from SFRSTCR where SFRSTCR_RSTS_CODE = (select STVRSTS_CODE from STVRSTS where STVRSTS_INCL_SECT_ENRL = 'Y') and SFRSTCR_TERM_CODE = '^' GROUP BY SFRSTCR_PIDM;
